[project]
name = "graph-rag-chatbot"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[[tool.uv.index]]
url = "https://pypi.org/simple"
priority = "primary"

[tool.uv.workspace]
members = [
    "interfaces",
    "frontend",
    "backend",
]

